<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Gustavo-Ortiz.local" name="TestCases.DeleteContentTest" tests="1" failures="1" timestamp="25 Oct 2016 23:17:29 GMT" time="14.765" errors="0">
  <testcase name="Add_New_Content_test" time="14.765" classname="TestCases.DeleteContentTest">
    <failure type="java.lang.AssertionError" message="expected [null] but found [By.xpath: /html/body/div[2]/div[1]/nav/div/div[2]/ul[1]/li/div/div[2]/div/div[1]/div[3]/div[1]/div[2]/div/div/div/div/div/div/div[2]/div[1]/table/tbody/tr/td[3]/span]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [By.xpath: /html/body/div[2]/div[1]/nav/div/div[2]/ul[1]/li/div/div[2]/div/div[1]/div[3]/div[1]/div[2]/div/div/div/div/div/div/div[2]/div[1]/table/tbody/tr/td[3]/span]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotSame(Assert.java:492)
	at org.testng.Assert.assertNull(Assert.java:428)
	at org.testng.Assert.assertNull(Assert.java:417)
	at TestCases.DeleteContentTest.Add_New_Content_test(DeleteContentTest.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- Add_New_Content_test -->
</testsuite> <!-- TestCases.DeleteContentTest -->
